[workspace]
resolver = "2"

members = [
    "hello_world",
    "rust_book/basics",
    "webdev/leptos/leptos-tutorial",
    "macros/declerative",
    "macros/procedural-basic",
    "macros/make-public",
    "macros/make-private",
]
