[package]
name = "bakery-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
sea-orm = {version="0.12.15" , features = [ "sqlx-mysql", "runtime-async-std-native-tls", "macros", "mock" ]}
sea-orm-migration = "0.12.15"
rocket = {version="0.5.1", features = ["json"]}
